# Generated by Django 6.1 on 2026-08-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_notification_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(choices=[('Confirmation', 'Confirmation'), ('Reschedule Notice', 'Reschedule Notice'), ('Cancellation Notice', 'Cancellation Notice'), ('No-Show Notice', 'No-Show Notice'), ('24 Hours Before', '24 Hours Before'), ('2 Hours Before', '2 Hours Before'), ('Follow-Up', 'Follow-Up')], max_length=40),
        ),
    ]
